### ISSUE TITLE
How to make AS Windows work

### ISSUE THREAD

**Issue by zarcha** [TylerWilley/flipper-f-com#5]
Hey, im the creator of AT and AS for windows, we send the word "ready" and expect the com to return text including the string "ready". This is different than AT since i don't really maintain AT as much as i do AS now. But without that "ready" text it will never detect the flipper. Hope that helps! good luck!

**Comment by TylerWilley** [comment]
Oh this is really helpful, thank you!

**Comment by TylerWilley** [comment]
Fixed in 63b5f9ae6fe0d347d21581d48ee36bbf51ac3a72
