### ISSUE TITLE
App Store Request & New Icon

### ISSUE THREAD

**Issue by Az-Neter** [TylerWilley/flipper-f-com#7]
Attached is a new icon so you don't have to use the badusb one (it's supposed to be Botamon but it looks more like a generic ghost).
The icon should be the proper size (10x10pix) but you'll need to rename it, both the file and within your app, if you choose to use it.

Are you willing to update your app so it can get put on the ofw flipper app store? 
If you need a guide for doing this, Derek Jamison aka codeallnight on YouTube and discord has a lot of info to help.
It would be very helpful for showcasing your app to more users and getting some extra support in developing it.

![Untitled153_20240405001628.png](https://github.com/TylerWilley/flipper-f-com/assets/119499525/8cedda8e-7221-43e2-8ee0-34ab70d4ed8f)

**Comment by TylerWilley** [comment]
I did get the icon updated with one someone else suggested (it's now the digimon icon)

I will eventually get it listed on the store, I'd like to get the digirom converter integrated before that point as it makes re-using codes you capture possible without having to export them off device first.

**Comment by Az-Neter** [comment]
Keep up the great work! I'm looking forward to integrating this tool with some stuff I'm making as well.

**Comment by Az-Neter** [comment]
Here's a more intuitive visualization of the circuit.
For being so simple, this is an easy circuit to mess up. The document showing the pins crossed adds to the confusion.

Use or remake this as you see fit, or just keep it here for people to stumble on.

![Untitled281_20240621022702.png](https://github.com/TylerWilley/flipper-f-com/assets/119499525/fbd7c1d9-5080-4264-a4aa-74c5cf88c534)
